# Generated by Django 6.0.4 on 2026-04-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('pdf', models.FileField(blank=True, upload_to='projects/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_types', models.ManyToManyField(to='searchitportfolio.clienttype')),
                ('media_types', models.ManyToManyField(to='searchitportfolio.mediatype')),
            ],
        ),
    ]
