# Generated by Django 4.2.19 on 2026-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchitportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credits',
            field=models.TextField(blank=True),
        ),
    ]
