# Generated by Django 4.2.19 on 2026-04-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchitportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='projects/pdfs/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='searchitportfolio.project')),
            ],
        ),
    ]
