# Generated by Django 4.2.19 on 2026-05-19 10:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchitportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectasset',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
