# Generated by Django 4.2.19 on 2026-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchitportfolio', '0002_project_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='hide_from_search',
            field=models.BooleanField(default=False),
        ),
    ]
